== Developer Manual
This developer manual includes code examples, hardware details, and guidelines to your contribution to the project.

=== 1. Hardware
This machine features a 128x64 LCD screen, five buttons, 3 LEDs and 125 bytes of SRAM and EEPROM.

=== 2. Software development

==== 2.1 Environment
The environment is a collection of four tools: the https://cc65.github.io[cc65 toolchain], https://gitlab.com/3dgoose/librock[the official SDK (librock)], an editor of your choice, and an optional make utility.

cc65 includes the compiler (cc65), assembler (ca65), linker (ld65), archiver (ar65) and simulator (sim65).

Any editor can be used, from `vi` to Eclipse. I use Vim.

The GNU Make is optional but recommeneded.

==== 2.2 Program optimization
Programs targeting this device should be optimized. The preferred language is 65(c)02 Assembly due to it's compact binary size and execution speed.

==== 2.3 Examples
A simple adder that prints the output :
[source,assembly]
----
.import _printf
.import pushax
.export _main

.segment "RODATA"
msg:
    .byte "The result is: %d", 10, 0

.segment "BSS"
res: .res 2

.segment "CODE"
.proc _main: near

    ; Load n1 (270) into A
    lda #<270
    sta res      ; LSB
    lda #>270
    sta res+1    ; MSB

    ; Add n2 (30)
    clc
    lda res
    adc #<30
    sta res
    lda res+1
    adc #>30
    sta res+1

    ; Print the result
    lda #<msg
    ldx #>msg
    jsr pushax

    lda res
    ldx res+1
    jsr pushax

    ldy #$04
    jsr _printf

    rts
.endproc
----

==== 2.4 librock
`librock` is the official SDK for the rock65. It contains subroutines for mathematics, I/O (screen, buzzer, rtc) and macros.

==== 2.5 Program execution

The EEPROM contains a bootloader that will wait for a program coming from the FTDI (here, FT232RL) and transfer it to the SRAM. Although this is the "default" method, you can flash the EEPROM with a program and run it on rock65 autonomously, without needing a computer connected. 
